### PR TITLE
add contribution instructions to README

### PR DESCRIPTION
**Pull request by nodiscc**
* fixes https://github.com/RequestPolicyContinued/requestpolicy/issues/542
 * add GPLv3 license text
 * based on https://github.com/contribute-md/contribute-md-template/blob/master/contribute.md

### CODE REVIEW

**Comment by myrdd** [comment]
Thanks for the PR, looks good! :) Some issues:

- There is already [src/LICENCE](https://github.com/RequestPolicyContinued/requestpolicy/blob/dev-1.0/src/LICENSE) and [src/LICENCE.gpl](https://github.com/RequestPolicyContinued/requestpolicy/blob/dev-1.0/src/LICENSE.gpl). I think you're right, they should be in the root directory. IMHO the two files shoud not be merged, but it makes no big difference.
- see https://github.com/myrdd/requestpolicy/commit/86ce3db2c8f4e7c74b556b9a9cba7e70c21c230e

So you've created a bountysource account. Nice. :)

**Comment by nodiscc** [comment]
Ah well I didn't notice the license files in src/. I think we should move _all_ authorship/license information to a single COPYING file, like I did at https://github.com/shaarli/Shaarli/blob/master/COPYING

I'll add your commit to the PR.

Bountysource automatically creates a bountysource project for all github repos, including issues etc. I had admin access to the RequestPolicyContinued bs project as soon as I logged in with github. You should have admin access as well.

**Comment by myrdd** [comment]
> I think we should move all authorship/license information to a single COPYING file, like I did at https://github.com/shaarli/Shaarli/blob/master/COPYING

If you also mean the licence headers in the source files I disagree. [Here](https://www.gnu.org/licenses/gpl-faq.html#NoticeInSourceFile) are some arguments. However, we could decide whether to maintain copyright information (a) per file or (b) centralized.

After reading [this article](https://www.softwarefreedom.org/resources/2012/ManagingCopyrightInformation.html) about Managing Copyright Information I think we should go with a hybrid approach, i.e. having license headers in each file, containing a copyright line like this: (copied from [here](https://www.softwarefreedom.org/resources/2012/ManagingCopyrightInformation.html#maintaining-centralized-copyright-notices))

> Copyright 2012 The Foo Project Developers. See the COPYRIGHT file at the top-level directory of this distribution and at http://example.org/project/COPYRIGHT.

We might have one line for 2008-2012 (RequestPolicy) and another for 2014-2015 (RequestPolicy Continued). Then we'll need the COPYRIGHT file, e.g. [like in debian](https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/).

But to be honest, I'm not quite certain to which detail the copyright information should be. It seems tedious to specify which files have been edited by whom. Also: what do the years mean, e.g. in [Sharrrli's COPYING file](https://github.com/shaarli/Shaarli/blob/master/COPYING) – have been all of them main developers in those years?

**Comment by nodiscc** [comment]
@myrdd I did some changes to the LICENSE file (see commits above) and added your commit to the PR. I think having all copyright info in one file is fine, but I could split it in several files (naming?).

> have been all of them main developers in those years?

No, and that's a problem we also had at https://github.com/az0/cleanerml/pull/56. As said there, copyright years for each author should only be years when the author actually contributed to the file. I can't see a simple way to do this. I'm looking for an automated tool to generate a proper copyright file.

Let me know if you have any ideas or remarks.

**Comment by myrdd** [comment]
Hi @nodiscc thanks for the changes. But why did you put the LGPL into that file? Is there a file licensed by that license?
Other than that, I think we can merge the PR.

> Edit: should I rebase this on top of dev-1.0-e10s-and-restartless ?

No, please merge it onto the main development branch.

> copyright years for each author should only be years when the author actually contributed to the file

I think that's a good practice. So we should update the license headers in each file.

**Comment by nodiscc** [comment]
> why did you put the LGPL into that file

The flag logo is based on Crystal Project, which is LGPL: https://github.com/nodiscc/requestpolicy/commit/e5830393fcaff092de3a8002acfb4668e662cb1a#diff-9879d6db96fd29134fc802214163b95aR29

> we should update the license headers in each file

Yes I'd like something that does this automatically for all my scripts/sources. I've found a plugin for my editor https://github.com/lifted-studios/AutoCopyright which doesn't seem to work. A command-line tool to do this would probably be cool (could be used as a git commit hook). Though a 1-year difference in the copyright header doesn't change much. $greedycompany would be able to un-GPL the source in 69 years instead of 70.

Good to merge, then.

**Comment by myrdd** [comment]
> The flag logo is based on Crystal Project, which is LGPL

OK, I've missed that.

> I'd like something that does this automatically

That would be nice indeed. However, I think that not each contribution is significant enough to update the license header. This would In general I think adding the copyright lines manually would be OK. I think not every contribution should lead to a new copyright line. That condition would make it more difficult to automate updating the license headers, don't you think? Let's discuss that at #607.

**Pull request merged**
