### PR TITLE
Fixes Issue #865 : WE transition: Implement "fake" `browser.runtime.getURL()` function

### PR DESCRIPTION
**Pull request by jrrdev**
Implements Api.browser.runtime.getURL() and adds corresponding unit tests.

**Be aware that currently:**
* `getUrl("/content/foo/bar.css")` is mapped into `chrome://rpcontinued/content/foo/bar.css` and not `chrome://rpcontinued/foo/bar.css` (see [this comment](https://github.com/RequestPolicyContinued/requestpolicy/issues/865#issuecomment-346616643))
* Matching for /content/settings is case sensitive (see [this test case](https://github.com/jrrdev/requestpolicy/blob/72bf386205b4f340ca9400b94f1256a558fbebbc/tests/unit/test-webextension-fake-api.js#L101-L105))
* Leading / and ./ are ignored (`/content/foo`is the same as `content/foo`, see [this](https://github.com/jrrdev/requestpolicy/blob/72bf386205b4f340ca9400b94f1256a558fbebbc/tests/unit/test-webextension-fake-api.js#L47-L57) and [this](https://github.com/jrrdev/requestpolicy/blob/72bf386205b4f340ca9400b94f1256a558fbebbc/tests/unit/test-webextension-fake-api.js#L131-L141))
* HTML files in a subdir of /content/settings are mapped to chrome:// (see [this](https://github.com/jrrdev/requestpolicy/blob/72bf386205b4f340ca9400b94f1256a558fbebbc/tests/unit/test-webextension-fake-api.js#L89-L93))

If any of this specs is incorrect, please tell me and I will correct it :-)

### CODE REVIEW

**Comment by myrdd** [comment]
Wow, I didn't expect you to create tests for that function, but that's great! :)

> getUrl("/content/foo/bar.css") is mapped into chrome://rpcontinued/content/foo/bar.css and not chrome://rpcontinued/foo/bar.css (see this comment)

That's completely correct! :)

**Comment by jrrdev** [comment]
With my past experience I found out that regex can be bitch :-) (lot of bugs can occur if not constructed properly), that why I made tests just to be sure.
Also wanted to play around with mocha & sinon as it was my first time ^^

**Comment by myrdd** [comment]
> Also wanted to play around with mocha & sinon as it was my first time ^^

Did you run the tests using `make unit-tests`?
Btw, did you also run `make lint`?

**Comment by jrrdev** [comment]
Oops didn't `make lint`, I will fix those issues later this day:
`
/requestpolicy/src/conditional/legacy/content/web-extension-fake-api/models/api.js
  251:1   error  Line 251 exceeds the maximum line length of 80  max-len
  260:47  error  Block must not be padded by blank lines         padded-blocks
  263:1   error  Line 263 exceeds the maximum line length of 80  max-len
  265:1   error  Line 265 exceeds the maximum line length of 80  max-len
  267:1   error  Line 267 exceeds the maximum line length of 80  max-len
  267:60  error  Unnecessary escape character: \/                no-useless-escape
  274:1   error  Trailing spaces not allowed                     no-trailing-spaces
`

For the unit tests, I ran `make mocha` but it seems to give same results as `make unit-tests`. Btw I updated [the wiki](https://github.com/RequestPolicyContinued/requestpolicy/wiki/Setting-up-a-development-environment#mocha-unit-tests)

**Comment by myrdd** [comment]
> Btw I updated the wiki

Great!! :)

> I ran make mocha but it seems to give same results as make unit-tests.

Yes, true. I've created many aliases :D

**Comment by myrdd** [comment]
@jrrdev FYI: https://github.com/RequestPolicyContinued/requestpolicy/commit/43338314b914a2b852097256b44e4a275d7b8698. I've fixed the remaining linter issues. I also fixed the linting issues on the test files, which were not checked due to the "src/" linting issue. ;)

**Pull request merged**
