### PR TITLE
Convert .properties to messages.json

### PR DESCRIPTION
**Pull request by beriain**
Hi!

I have created a quick and dirty python script to convert the .properties files to messages.json, as requested in #876 . I share it here in case someone want's to check if there is something wrong, but at a first glance, it seems to me the conversion is correct.

```python
print("Converting from .properties to messages.json...")

#Path to source .properties file
src = "/requestpolicy/src/locale/en-US/requestpolicy.properties"
#Path to translated .properties file
trs = "/requestpolicy/src/locale/de/requestpolicy.properties"
#Path to messages.json file
dst = "/requestpolicy/src/locale/de/messages.json"
#List to store the source strings
strings = []
#List to store the translations
translations = []

#Read the source strings
with open(src, "r") as s:
    strings = s.read().split("\n")

#Read the translations
with open(trs, "r") as t:
    translations = t.read().split("\n")

#Write messages.json file
with open(dst, "w") as d:
    d.write("{\n")
    for x in range(0, len(strings)-1):
        #If the string is translated add it
        if (strings[x].split("=")[1] != translations[x].split("=")[1]):
            d.write("\t\"" + strings[x].split("=")[0] + "\": {\n")
            d.write("\t\t\"message\": \"" + strings[x].split("=")[1] + "\",\n")
            d.write("\t\t\"description\": \"" + translations[x].split("=")[1] + "\"\n")
            if x != len(strings)-2:
                d.write("\t},\n\n")
            else:
                d.write("\t}\n\n")
    d.write("}")

print("Done.")
```

### CODE REVIEW

**Comment by myrdd** [comment]
Great! Thanks @beriain!

I've applied some corrections and fixes, this is the new script:

```python
#!/usr/bin/python3

import os

print("Converting from .properties to messages.json...")


def src_path(locale):
    return "src/locale/{}/requestpolicy.properties".format(locale)


def dest_path(locale):
    locale = locale.replace('-', '_')
    return "src/conditional/webextension/_locales/{}/messages.json".format(locale)


def map_str(str_):
    return (
        str_
        .replace('%S', '$1')
        .replace('%1$S', '$1')
        .replace('%2$S', '$2')
        .replace(r'\"', r'"')
        .replace('"', r'\"')
    )

# Path to source .properties file
default_locale = 'en-US'

locales = [
    'de', 'en-US', 'eo', 'es-ES', 'es-MX', 'eu', 'fr', 'it', 'ja', 'ko-KR',
    'lv-LV', 'nl', 'pl', 'pt-BR', 'ru-RU', 'sk-SK', 'sv-SE', 'tr', 'uk-UA',
    'zh-CN', 'zh-TW',
]


TAB = '  '

for locale in locales:
    print(locale)

    # List to store the source strings
    strings = []
    # List to store the translations
    translations = []

    # Read the source strings
    with open(src_path(default_locale), "r") as s:
        strings = s.read().split("\n")

    # Read the translations
    with open(src_path(locale), "r") as t:
        translations = t.read().split("\n")

    strings = [map_str(s) for s in strings]
    translations = [map_str(s) for s in translations]

    destfile_path = dest_path(locale)
    destdir_path = os.path.dirname(destfile_path)

    if not os.path.exists(destdir_path):
        os.makedirs(destdir_path)

    # Write messages.json file
    with open(destfile_path, "w") as d:
        d.write("{\n")
        entries = []
        for x in range(0, len(strings)-1):
            # If the string is translated add it
            if locale == default_locale or strings[x].split("=")[1] != translations[x].split("=")[1]:
                entry = ""
                entry += (TAB*1) + "\"" + strings[x].split("=")[0] + "\": {\n"
                entry += (TAB*2) + "\"message\": \"" + translations[x].split("=")[1] + "\",\n"
                entry += (TAB*2) + "\"description\": \"" + strings[x].split("=")[1] + "\"\n"
                entry += TAB + "}"
                entries.append(entry)
        d.write(",\n\n".join(entries))
        d.write("\n}\n")

print("Done.")
```

**Comment by myrdd** [comment]
Done. Thank you @beriain :) See https://github.com/myrdd/requestpolicy/commit/b97890e5aaf2d1fbdacc08dc29a0d4019586c1d6

**Comment by myrdd** [comment]
I've extended the script to parse `install.rdf`. See https://gist.github.com/myrdd/d3d3778a869c81938a89b889dee7e77a

(I also changed the code to allow different key orderings when comparing `.properties` files, but as it turned out, it was not necessary.)

**Comment by beriain** [comment]
Wow, so much better! You have improved the script a lot!

Thank you very much for your work, RequestPolicy is the most important Firefox extension for me, and I would love to be able to help more in the WE transition. Unfortunately I'm not a very skilled programmer and I don't have too much free time, but if I see something where I could help I will try to give a hand.

**Comment by myrdd** [comment]
@beriain great! I'll create more easy-to-solve issues, which you can track in https://github.com/RequestPolicyContinued/requestpolicy/issues/704 :)

**Pull request closed without merging**
